---
blank_issues_enabled: false

contact_links:
  - name: Cleaner Data
    url: https://github.com/openelections/openelections-data-la
    about: This is where we store the data from this repo once we clean it.
  - name: Cleanest Data
    url: https://github.com/openelections/openelections-results-la
    about: The best version of the state election data
  - name: OpenElections Website
    url: http://openelections.net/
    about: The main OpenElections website. Head here for questions and to learn more about the project.
